gantt
todayMarker off
dateFormat YYYY
axisFormat %Y
title 三次浪潮

section 史前文明

推理期: done, 1950, 1975
1950 图灵测试: 1950, milestone
1956 达特茅斯会议: 1956, milestone
1963 逻辑理论家证明《数学原理》中的52条定理: 1963, milestone
1975 西蒙、纽厄尔获图灵奖: 1975, milestone

知识期: done, 1965, 1990
1965 费根鲍姆研制DENDRAL: 1965, milestone
1969 知识系统兴起: 1969, milestone
1975 专家系统兴起: 1975, milestone
1994 费根鲍姆获图灵奖: 1994, milestone

学习期: active, 1984, 2030
1984 瓦利安特提出PAC学习框架: 1984, milestone
1985 珀尔提出贝叶斯网的信念传播算法: 1985, milestone
1986 反向传播算法被重新提出: 1986, milestone
1995 以支持向量机为代表的统计学习兴起: 1995, milestone
2010 瓦利安特获图灵奖: 2010, milestone
2011 珀尔获图灵奖: 2011, milestone
2012 深度学习兴起: 2012, milestone
2018 辛顿等获图灵奖: 2018, milestone
